### ISSUE TITLE
Error while initializing SmartSleep, exception: 'tuple' object has no attribute 'get_device_info'

### ISSUE THREAD

**Issue by ragnarekmix** [wylek/smartsleep#10]
Hi,
I'm getting this error at setup attempt
Logger: custom_components.smartsleep
Source: custom_components/smartsleep/__init__.py:59
Integration: Philips SmartSleep ([documentation](https://github.com/wylek/smartsleep), [issues](https://github.com/wylek/smartsleep/issues))
First occurred: 12:10:54 PM (1 occurrences)
Last logged: 12:10:54 PM

Error while initializing SmartSleep, exception: 'tuple' object has no attribute 'get_device_info'
Can you please help me?

This is my config
smartsleep:
  host: 192.168.0.19
  name: device.smartsleep

**Comment by austinwylie** [comment]
I'm getting the same error after setting up the integration in the UI.

- Home Assistant 2022.8.6
- SmartSleep model HF3670

**Comment by Amnesia2Bad** [comment]
This fixed it for me.
https://github.com/wylek/smartsleep/pull/9/commits/ec01c472b506c070fa87e65e169187d4688acecf
