### ISSUE TITLE
Integration Failed

### ISSUE THREAD

**Issue by Sn0wfir3** [wylek/smartsleep#17]
Missing constants while setting up:
CONF_NAME 
CONF_HOST
UPDATE_TIME
PLATFORMS

after re adding the constants it also fails. 
tried deleting previous integration after updating.

Only solution was to downgrade to previous state. (71635e343c91f6500746e492749f4eb3498f1630)

**Comment by wylek** [comment]
Hey @Sn0wfir3, this should be fixed now. Apologies, I had an incomplete merge from upstream.
