### ISSUE TITLE
Sunset mode

### ISSUE THREAD

**Issue by TheValist** [wylek/smartsleep#26]
Hi, 
How exactly does sunset mode work?

I've got this error in the logs (not sure if related):
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smartsleep/light.py", line 38, in async_setup_entry
    SmartSleepSunset(coordinator, unique_id, name, device_info, "sunset")
TypeError: SmartSleepSunset.__init__() takes 5 positional arguments but 6 were given

Thanks

**Comment by tomerh2001** [comment]
+1 can't seem to understand how to use sunset

**Comment by tomerh2001** [comment]
Is there any update about the sunset feature? I really want that feature for my day-to-day...

**Comment by TheValist** [comment]
Any news?

**Comment by wylek** [comment]
---

# 🛑 DEPRECATION NOTICE

This fork of the original Somneo component from @theneweinstein is no longer maintained.

➡️➡️➡️ [Somneo custom integration](https://github.com/theneweinstein/somneo)

---
