### ISSUE TITLE
deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by dersch81** [wylek/smartsleep#32]
WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from smartsleep, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead

can you adjust this?

**Comment by wylek** [comment]
---

# 🛑 DEPRECATION NOTICE

This fork of the original Somneo component from @theneweinstein is no longer maintained.

➡️➡️➡️ [Somneo custom integration](https://github.com/theneweinstein/somneo)

---
